version: '3.8'
services:
  wordpress:
    image: wordpress:${WORDPRESS_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME:-wordpress}
    volumes:
      - wp_files:/var/www/html
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
      - ./themes/:/var/www/html/wp-content/themes/
      - ./themes/dev-theme:/var/www/html/wp-content/themes/dev-theme/
    environment:
      WORDPRESS_DB_NAME: ${COMPOSE_PROJECT_NAME:-wordpress}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-mysql}
      WORDPRESS_DB_USER: ${DATABASE_USER:-root}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD:-password}
      WORDPRESS_DEBUG: 1
      APACHE_RUN_GROUP: '#33'
      APACHE_RUN_USER: '#33'
    # user: '33:33'
    depends_on:
      - mysql
    restart: always
    ports:
      - ${HTTP_PORT:-80}:80

  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-password}
      MYSQL_USER: ${DATABASE_USER:-root}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-password}
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME:-wordpress}
    restart: always
    ports:
      - ${MYSQL_PORT:-3306}:3306

  wpcli:
    build: ./wpcli/
    image: wpcli
    container_name: ${COMPOSE_PROJECT_NAME}_wpcli
    volumes:
      - wp_files:/var/www/html
    working_dir: /var/www/html

  # Check availability of essential services
  # healthcheck:
  #   image: wpcli
  #   build: ./wpcli/
  #   container_name: ${COMPOSE_PROJECT_NAME}_healthcheck
  #   command: sh -c "/wait"
  #   environment:
  #     WAIT_HOSTS: mysql:${MYSQL_PORT:-3306}, wordpress:${HTTP_PORT:-80}
  #     WAIT_BEFORE_HOSTS: ${WAIT_BEFORE_HOSTS:-30}
  #     WAIT_AFTER_HOSTS: ${WAIT_AFTER_HOSTS:-15}
  #     WAIT_HOSTS_TIMEOUT: ${WAIT_HOSTS_TIMEOUT:-300}
  #     WAIT_SLEEP_INTERVAL: ${WAIT_SLEEP_INTERVAL:-30}
  #     WAIT_HOST_CONNECT_TIMEOUT: ${WAIT_HOST_CONNECT_TIMEOUT:-30}


volumes:
    wp_files:
    db_data: